FROM rabbitmq:3-management-alpine

RUN rabbitmq-plugins enable --offline rabbitmq_shovel \
    && rabbitmq-plugins enable --offline rabbitmq_shovel_management

EXPOSE 5672 15672 25672


CMD ["rabbitmq-server"]

